### ISSUE TITLE
constant run errors

### ISSUE THREAD

**Issue by russellprice** [unt-sysprog-team/major-assignment-1#22]
currently typing **grep text.txt** has caused the program to never stop running, will not ask for a prompt just blank

**Comment by edgariscoding** [comment]
@russellprice, I believe this isn't an error with our program. Try running that exact command on the CSCE machine, it'll do the same thing. I think it's because it's not proper syntax for the grep command. 

**These are the contents of `test file`:**

```
blah one two three
```

**This CSCE terminal command hangs:**
![Sample1](http://i.imgur.com/OeI4719.png)

**But this CSCE terminal command runs successfully:**
![Sample2](http://i.imgur.com/Z6yoHoT.png)

**These are the contents of `test/batch`:**

```
ps ;ls -l ;     ls
who  ;  ;ls ; date;ps ; ls -l
```

**This terminal command from our project hangs:**
![Sample3](http://i.imgur.com/qo1M0ib.png)

**And this terminal command from our project runs successfully:**
![Sample4](http://i.imgur.com/k5LmggB.png)

Let me know what you think.

-- Edgar

**Comment by edgariscoding** [comment]
Discussed with @russellprice, will close issue since the Unix shell has the same behavior.
